import 'brew.dart';

class BrewsBrain {
  List<Brew> brews = [
    Brew(coffee: "Arabica", temperature: 78, time: 3, weight: 25, description: "Morbi et aliquet nunc. Vivamus porttitor venenatis egestas. Morbi at metus ut dui interdum tristique. Etiam vel urna dolor. Fusce porttitor, metus non ultrices mollis, nisi purus bibendum tortor, in auctor mi nunc sit amet tortor. Duis facilisis tortor non elit lobortis commodo. Pellentesque at quam libero."),
    Brew(coffee: "Indica", temperature: 73, time: 4, weight: 12, description: "Morbi et aliquet nunc. Vivamus porttitor venenatis egestas. Morbi at metus ut dui interdum tristique. Etiam vel urna dolor. Fusce porttitor, metus non ultrices mollis, nisi purus bibendum tortor, in auctor mi nunc sit amet tortor. Duis facilisis tortor non elit lobortis commodo. Pellentesque at quam libero."),
    Brew(coffee: "Africa", temperature: 91, time: 1, weight: 31, description: "Morbi et aliquet nunc. Vivamus porttitor venenatis egestas. Morbi at metus ut dui interdum tristique. Etiam vel urna dolor. Fusce porttitor, metus non ultrices mollis, nisi purus bibendum tortor, in auctor mi nunc sit amet tortor. Duis facilisis tortor non elit lobortis commodo. Pellentesque at quam libero."),
    Brew(coffee: "Tropica", temperature: 96, time: 5, weight: 33, description: "Morbi et aliquet nunc. Vivamus porttitor venenatis egestas. Morbi at metus ut dui interdum tristique. Etiam vel urna dolor. Fusce porttitor, metus non ultrices mollis, nisi purus bibendum tortor, in auctor mi nunc sit amet tortor. Duis facilisis tortor non elit lobortis commodo. Pellentesque at quam libero."),
    Brew(coffee: "Malysia", temperature: 85, time: 8, weight: 42, description: "Morbi et aliquet nunc. Vivamus porttitor venenatis egestas. Morbi at metus ut dui interdum tristique. Etiam vel urna dolor. Fusce porttitor, metus non ultrices mollis, nisi purus bibendum tortor, in auctor mi nunc sit amet tortor. Duis facilisis tortor non elit lobortis commodo. Pellentesque at quam libero."),
    Brew(coffee: "Tunesia", temperature: 88, time: 5, weight: 31, description: "Morbi et aliquet nunc. Vivamus porttitor venenatis egestas. Morbi at metus ut dui interdum tristique. Etiam vel urna dolor. Fusce porttitor, metus non ultrices mollis, nisi purus bibendum tortor, in auctor mi nunc sit amet tortor. Duis facilisis tortor non elit lobortis commodo. Pellentesque at quam libero."),
    Brew(coffee: "Java", temperature: 102, time: 3, weight: 22, description: "Morbi et aliquet nunc. Vivamus porttitor venenatis egestas. Morbi at metus ut dui interdum tristique. Etiam vel urna dolor. Fusce porttitor, metus non ultrices mollis, nisi purus bibendum tortor, in auctor mi nunc sit amet tortor. Duis facilisis tortor non elit lobortis commodo. Pellentesque at quam libero."),
    Brew(coffee: "Guantao", temperature: 90, time: 2, weight: 15, description: "Morbi et aliquet nunc. Vivamus porttitor venenatis egestas. Morbi at metus ut dui interdum tristique. Etiam vel urna dolor. Fusce porttitor, metus non ultrices mollis, nisi purus bibendum tortor, in auctor mi nunc sit amet tortor. Duis facilisis tortor non elit lobortis commodo. Pellentesque at quam libero."),
  ];
}